apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AngularCodespace
  description: codespace sample
  annotations:
    github.com/project-slug: KPRASH14/Angular-Codespace
#    sonarqube.org/project-key:
#    fossa.io/project-name:
spec:
  type: website
  lifecycle: experimental
  owner: 
